models:
    image: tp33/django
    external_links:
      -  mysql:db
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    command: >
        bash -c "cd beerDelivery && python manage.py makemigrations && python3 manage.py migrate
        && python manage.py loaddata db.json
        && mod_wsgi-express start-server --working-directory ./app/beerDelivery --reload-on-changes ./app/beerDelivery/beerDelivery/beerDelivery/wsgi.py"
    tty: true

